version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: user_withdrawal_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: user_withdrawal
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: user_withdrawal_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  # PHP Hyperf Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: user_withdrawal_backend
    ports:
      - "9501:9501"
    volumes:
      - ./backend:/opt/www
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=user_withdrawal
      - DB_USERNAME=app_user
      - DB_PASSWORD=app_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    depends_on:
      - mysql
      - redis
    networks:
      - app_network

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: user_withdrawal_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:9501
    depends_on:
      - backend
    networks:
      - app_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: user_withdrawal_nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

volumes:
  mysql_data:
  redis_data:

networks:
  app_network:
    driver: bridge
